import pandas as pd
S1 = pd.Series([12, 23, 34, 45, 55, 76, 80, 92, 41, 69, 56])
print("All elements")
print(S1[:])
print('print part of series')
print(S1[2:6])
print("First 4 elements")
print(S1[:4])
print("Fifth element to final element")
print(S1[5:])
print("Alternative elements")
print(S1[0:11:2])
print("Check outof range index")
print(S1[8:15])
print("Using upper Negative index")
print(S1[3:-5])
print("Using negative index to print in reverse order")
print(S1[:-6])
print("Using lower negative index")
print(S1[-4:])
print("Display between two negative indexes")
print(S1[-7: -2])
print("skip two elements in forward direction")
print(S1[::3])
print("skip two elements in reverse direction")
print(S1[::-3]) 
