import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
mat1 = np.matrix(arr1)
print("2X2 matrix is\n", mat1)
arr2 = np.array([[1, 2, 3],[6, 1, 4],[5, 6, 8]])
mat2 = np.matrix(arr2)
print("3X3 matrix is\n", mat2)
print("Transpose of 2X2 matrix is\n", np.transpose(arr1))
print("Transpose of 3X3 matrix is\n", np.transpose(arr2))
print("Inverse of 2X2 matrix\n", np.linalg.inv(mat1))
print("Inverse of 3X3 matrix\n", np.linalg.inv(mat2))
print("det of 2X2 matrix is \n",np.linalg.det(mat1))
print("Det of 3X3 matrix is\n",np.linalg.det(mat2))
print("Maximum value of 2X2 matrix is\n",mat1.max())
print("Minimum value of 2X2 matrix is\n",mat1.min())
print("sum of the 2X2 matrix is\n",mat1.sum())
print("product of 2X2 matrix is\n",mat1.prod())
print("sorting of 2X2 matrix is\n",np.sort(mat1))

